
---
- hosts: nodes
  vars:
    local_path: /home/jonsun/nodejs-project/nodejs
    project_path: /home/jonsun/www/nodejs
    nodejs_version: "12.x"
    distro: stretch
  tasks:

  - name: Create new folder
    file:
        dest: '{{ project_path }}'
        owner: jonsun
        group: jonsun
        mode: 0755
        state: directory

  - name: copy the nodejs files
    copy:
        source: '{{ local_path}}/{{ item }}'
        destionation: '{{ project_path }}/{{ item }}'
    with_items:
     - 'server.js'
     - 'client.js'
     - 'index.html'

  - name: Ensure apt-transport-https is installed.
    apt: name=apt-transport-https state=present
    sudo: yes

  - name: Add Nodesource apt key.
    apt_key:
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
      id: "68576280"
      state: present
    sudo: yes

  - name: Add NodeSource repositories for Node.js.
    apt_repository:
      repo: '{{ item }}'
      state: present
    with_items:
      - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ distro }} main"
      - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ distro }} main"
    register: node_repo
    sudo: yes

  - name: Update apt cache if repo was added.
    apt: update_cache=yes
    when: node_repo.changed
    sudo: yes
    

  - name: Ensure Node.js and npm are installed.
    apt: "name=nodejs={{ nodejs_version|regex_replace('x', '') }}* state=present"
    sudo: yes

  - name: Node.js app | Install PM2
    npm:
      name: pm2
      state: present
      path: '{{ project_path }}'
      global: yes
    sudo: yes

  - name: Node.js app | Install mysql
    npm:
      name: mysql
      state: present
      path: '{{ project_path }}'
    sudo: yes

  - name: Node.js app | Install express
    npm:
      name: express
      state: present
      path: '{{ project_path }}'
    sudo: yes
    

  - name: Node.js app | Install body-parser
    npm:
      name: body-parser
      state: present
      path: '{{ project_path }}'
    sudo: yes

  - name: NODE | Stop APP
    shell: pm2 stop all
    args:
        chdir: '{{ project_path }}'
    ignore_errors: yes

  - name: NODE | Start APP
    shell: pm2 start server.js --name server
    args:
        chdir: '{{ project_path }}'
    ignore_errors: yes
    